### ISSUE TITLE
A bug in the padding attribute

### ISSUE THREAD

**Issue by lewiis-web** [koukibadr/Motion-Toast#116]
When the title property is not set, only the description property is set, and`displaySideBar: false`, When the above conditions are met, setting the padding property will generate a bug, where the value corresponding to padding is the margin of the description, not the margin of the entire content area. This looks a bit strange! The code is as follows: `MotionToast.error(
                    description: const Text("验证码错误，请重新输入"),
                    position: MotionToastPosition.top,
                    height: 50,
                    iconSize: 30,
                    displaySideBar: false,
                    padding: const EdgeInsets.only(left: 50),
                  ).show(context);`

**Comment by koukibadr** [comment]
@lewiis-web for the error it's related to the height attribute when you set the height you need to provide also the width of the widget 
for the padding it's related to the whole toast and not the content inside it, as you said it's working margin rather than padding , I'll publish a new version updating the name of the attribute and adding a padding attribute related the the content

**Comment by koukibadr** [comment]
@lewiis-web I just published the 2.9.0 version with two changes: 
- `padding` is renamed to `margin`
- added `contentPadding` attribute a padding for the content inside the toast
